{'cdsl_trigger_score': {'cdsl': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 20],
    [[0.0, 0, False, '0', '0.0', 'False'], 0]],
   'else': [0]}},
 'indexed_name_match_trigger_score': {'indexed_name_match_score': {'null_check': [[0]],
   'empty_string_check': [[0]],
   'between_1': [[[0, 5], -50],
    [[5, 40], 0],
    [[40, 60], 10],
    [[60, 80], 20],
    [[80, 100], 30]],
   'else': [0]}},
 'email_first_seen_year_trigger_score': {'email_first_seen_year': {'null_check': [[0]],
   'empty_string_check': [[0]]},
  'email_first_seen_year_month_vintage': {'time_in_yrs': [['email_first_seen_year']],
   '==': [[[0], -40], [[1], 0], [[2, 3], 10], [[4, 5], 20]],
   'between_1': [[[5, 10], 30]],
   '>': [[10, 40]],
   'else': [0]}},
 'phone_email_first_seen_year_trigger_score': {'phone_email_first_seen_year': {'null_check': [[0]],
   'empty_string_check': [[0]]},
  'phone_email_first_seen_year_month_vintage': {'time_in_yrs': [['phone_email_first_seen_year']],
   '==': [[[0], -40], [[1], 0], [[2, 3], 10], [[4, 5], 20]],
   'between_1': [[[5, 10], 30]],
   '>': [[10, 40]],
   'else': [0]}},
 'phone_name_first_seen_year_trigger_score': {'phone_name_first_seen_year': {'null_check': [[0]],
   'empty_string_check': [[0]]},
  'phone_name_first_seen_year_month_vintage': {'time_in_yrs': [['phone_name_first_seen_year']],
   '==': [[[0], -40], [[1], 0], [[2, 3], 10], [[4, 5], 20]],
   'between_1': [[[5, 10], 30]],
   '>': [[10, 40]],
   'else': [0]}},
 'is_whatsapp_available_trigger_score': {'whatsapp': {'null_check': [[0]],
   '==': [[[0.0, 0, False, '0', '0.0', 'False'], -100],
    [[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 0]],
   'else': [0]}},
 'is_tax_payer_trigger_score': {'tax': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 70],
    [[0.0, 0, False, '0', '0.0', 'False'], -50]],
   'else': [0]}},
 'is_whatsapp_business_available_trigger_score': {'is_w_a_business': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 10],
    [[0.0, 0, False, '0', '0.0', 'False'], 0]],
   'else': [0]}},
 'is_postpaid_phone_trigger_score': {'number_billing_type': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 150],
    [[0.0, 0, False, '0', '0.0', 'False'], 0]],
   'else': [0]}},
 'phone_age_on_network_trigger_score': {'date_aon': {'null_check': [[0]]},
  'date_aon_month': {'time_in_months': [['date_aon']],
   '<=': [[6, -60]],
   'between_1': [[[6, 12], -40],
    [[12, 24], 0],
    [[24, 36], 40],
    [[36, 60], 50]],
   '>': [[60, 100]],
   'else': [0]}},
 'vpa_available_trigger_score': {'vpa_available': {'null_check': [[0]],
   '==': [[[0.0, 0, False, '0', '0.0', 'False'], -20],
    [[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 50]],
   'else': [0]}},
 'vpa_name_match_trigger_score': {'vpa_available': {'null_check': [[0]],
   '==': [[[0.0, 0, False, '0', '0.0', 'False'], 0]]},
  'phone_vpa_name': {'null_check': [[0]]},
  'input_name': {'null_check': [[0]]},
  'similarity_class': {'get_similarity_class': [['input_name',
     'phone_vpa_name']],
   '==': [[['0'], 0], [['1'], -20], [['2'], 10], [['3'], 30]],
   'else': [0]}},
 'has_multiple_email_with_phone_trigger_score': {'email_mapped_with_phone': {'null_check': [[0]],
   '==': [[[0], 0]],
   'between_1': [[[0, 3], 0], [[3, 6], 0]],
   '>': [[6, -50]],
   'else': [0]}},
 'di_phonedi_combined_trigger_score': {('digital_identity_score',
   'phone_name_d_i_score'): {'sequential_triggers': [True]},
  'digital_identity_score': {'null_check': [[0]],
   '<=': [[300, -30]],
   'between_1': [[[300, 600], -30]],
   '>': [[600, 10]]},
  'phone_name_d_i_score': {'null_check': [[0]],
   '<=': [[300, -30]],
   'between_1': [[[300, 600], -30]],
   '>': [[600, 10]]},
  'default_score': {'get_default_score': [0]}},
 'is_pan_email_present_trigger_score': {'pan_email_present': {'null_check': [[0]],
   '==': [[[0.0, 0, False, '0', '0.0', 'False'], -10],
    [[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 10]],
   'else': [0]}},
 'inactive_gst_trigger_score': {'inactive_gst_count': {'null_check': [[0]],
   '==': [[[0], 0], [[1], -20], [[2], -40], [[3], -60], [[4], -80]],
   '>=': [[5, -100]],
   'else': [0]}},
 'base_score': 450,
 'has_ported_trigger_score': {'number_has_porting_history': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True'], 40]],
   'else': [0]}},
 'has_flipkart_trigger_score': {'flipkart': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True'], 60],
    [[0.0, 0, False, '0', '0.0', 'False'],
     -10,
     {'flipkart_absent_tag': 'df03'}]],
   'else': [0]}},
 'is_ugly_bad_trigger_score': {'bad_ugly_match_found': {'null_check': [[0]],
   '==': [[['ugly'], -300], [['bad'], -20]],
   'else': [0]}},
 'phonename_first_seen_trigger_score': {'phone_name_first_seen_year': {'null_check': [[0]],
   'empty_string_check': [[0]]},
  'phone_name_first_seen_year_diff': {'time_in_yrs': [['phone_name_first_seen_year']],
   '==': [[[0], -60, {'phone_aon2_tag': 'di13'}],
    [[1, 2], 0],
    [[3], 50],
    [[4], 70]],
   '>=': [[5, 90]],
   'else': [0]}},
 'email_repuation_trigger_score': {'input_email': {'null_check': [[0]]},
  'email_first_seen_year_diff': {'time_in_yrs': [['email_first_seen_year']],
   '>=': [[5, 0]]},
  'email_num_count': {'numbers_count': [['input_email']]},
  ('email_first_seen_year_diff',
   'email_num_count'): {'combined_rule': [[['nan', 'NaN', None, ''],
     {'>': 5},
     -80,
     {'email_quality_tag': 'df06'}],
    [['nan', 'NaN', None, ''], {'<=': 5}, 0]]},
  'email_num_count2': {'numbers_count': [['input_email']],
   '>=': [[3, -80, {'email_quality_tag': 'df06'}]],
   'else': [0]}},
 'risky_fintech_ratio_trigger_score': {'risky_fintech_count': {'null_check': [[0]],
   '==': [[[0], 0]],
   '>': [[0, -50, {'risky_fintech_tag': 'df07'}]],
   'else': [0]}},
 'phone_recycled_trigger_score': {'phone_deactivated_days': {'null_check': [[0]],
   '<=': [[0, 0]],
   'between_1': [[[0, 200], -200], [[200, 400], -50]],
   '>': [[400, 100]],
   'else': [0]}},
 'has_mutual_funds_trigger_score': {'amc_count': {'null_check': [[0]],
   '>=': [[2, 60]],
   'else': [0]}},
 'pan_name_match_trigger_score': {'pan_name': {'null_check': [[0]]},
  'input_name': {'null_check': [[0]]},
  'similarity_class': {'get_similarity_class': [['input_name', 'pan_name']],
   '==': [[['0'], 0], [['1'], -50], [['2'], 50], [['3'], 50]],
   'else': [0]}},
 'phone_match_trigger_score': {'pan_phone': {'null_check': [[0]]},
  'input_phone': {'null_check': [[0]]},
  'cleaned_phone': {'clean_phone': [['pan_phone']]},
  ('cleaned_phone', 'input_phone'): {'phone_match': [[50]],
   'phone_unmatch': [[0]],
   'else': [0]}},
 'din_trigger_score': {'din': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 100],
    [[0.0, 0, False, '0', '0.0', 'False'], 0]],
   'else': [0]}},
 'udyam_trigger_score': {'udyam': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 100],
    [[0.0, 0, False, '0', '0.0', 'False'], 0]],
   'else': [0]}},
 'aadhar_trigger_score': {'pan_aadhar_present': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 30],
    [[0.0, 0, False, '0', '0.0', 'False'], 0]],
   'else': [0]}},
 'email_domain_trigger_score': {'pan_email_present': {'null_check': [[0]]},
  'email_domain': {'extract_domain': [['pan_email_present']],
   '==': [[['gmail.com',
      'yahoo.com',
      'rediffmail.com',
      'yahoo.com',
      'hotmail.com',
      'outlook.com',
      'ymail.com',
      'live.com',
      'icloud.com',
      'mail.com'],
     30]],
   'str_len_check': [[3, 10]],
   'else': [0]}},
 'email_match_trigger_score': {'pan_email_present': {'null_check': [[0]]},
  'input_email': {'null_check': [[0]]},
  ('pan_email_present', 'input_email'): {'email_match': [[30]],
   'email_unmatch': [[0]],
   'else': [0]}},
 'uan_available_trigger_score': {'uan_available': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 0],
    [[0.0, 0, False, '0', '0.0', 'False'], -100]],
   'else': [0]}},
 'phone_name_trigger_score': {'diff_phone_name_count': {'null_check': [[0]],
   '<=': [[2, 0]],
   '>': [[2, -30]],
   'else': [0]}},
 'phone_first_seen_trigger_score': {'phone_first_seen_year': {'null_check': [[0]],
   'empty_string_check': [[0]]},
  'phone_first_seen_year_month_vintage': {'time_in_yrs': [['phone_first_seen_year']],
   '==': [[[0], -70]],
   '>': [[0, 0]],
   'else': [0]}},
 'phone_email_match_trigger_score': {'phone_email_match': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 0],
    [[0.0, 0, False, '0', '0.0', 'False'], -30]],
   'else': [0]}},
 'is_indiamart_available_trigger_score': {'indiamart': {'null_check': [[0]],
   '==': [[[0.0, 0, False, '0', '0.0', 'False'], 0],
    [[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 70]],
   'else': [0]}},
 'is_instagram_available_trigger_score': {'instagram': {'null_check': [[0]],
   '==': [[[0.0, 0, False, '0', '0.0', 'False'], 0],
    [[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 20]],
   'else': [0]}},
 'is_paytm_available_trigger_score': {'paytm': {'null_check': [[0]],
   '==': [[[0.0, 0, False, '0', '0.0', 'False'], -20],
    [[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 30]],
   'else': [0]}},
 'email_num_count_tag': {'email_num_count': {'numbers_count': [['input_email']],
   '>': [[5, 'Dubious Email']]}},
 'flipkart_whatsapp_tag': {('flipkart',
   'whatsapp'): {'x_and_y': [[[0.0, 0, False, '0', '0.0', 'False'],
     [0.0, 0, False, '0', '0.0', 'False'],
     'Not Present on Whatsapp and Other relavant digital Platforms']]}},
 'phonename_first_seen_tag': {'phone_name_first_seen_year': {'empty_string_check': [['no tag']]},
  'phone_name_first_seen_year_diff': {'time_in_months': [['phone_name_first_seen_year']],
   '<=': [[6, 'Phone Picked up less than 6 Months']],
   'between_1': [[[6, 12], 'Phone Picked up less than 1 Year']]}},
 'is_whatsapp_flipkart_absent_trigger_score': {'flipkart': {'null_check': [[0]]},
  'whatsapp': {'null_check': [[0]]},
  ('whatsapp',
   'flipkart'): {'x_and_y': [[[0.0, 0, False, '0', '0.0', 'False'],
     [0.0, 0, False, '0', '0.0', 'False'],
     -150],
    [[0.0, 0, False, '0', '0.0', 'False'],
     [1.0, 1, True, '1', '1.0', 'True', 'postpaid'],
     0],
    [[1.0, 1, True, '1', '1.0', 'True', 'postpaid'],
     [0.0, 0, False, '0', '0.0', 'False'],
     0],
    [[1.0, 1, True, '1', '1.0', 'True', 'postpaid'],
     [1.0, 1, True, '1', '1.0', 'True', 'postpaid'],
     0]], 'else': [0]}},
 'is_demat_trigger_score': {'is_demat_available': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True', 'postpaid'], 20],
    [[0.0, 0, False, '0', '0.0', 'False'], 0]],
   'else': [0]}},
 'age_limit_trigger_score': {'pan_birth_date': {'null_check': [[0]]},
  'pan_birth_age': {'time_in_months': [['pan_birth_date']],
   '<': [[240, -20]],
   '>=': [[240, 0]],
   'else': [0]}},
 'has_swiggy_trigger_score': {'swiggy': {'null_check': [[0]],
   '==': [[[1.0, 1, True, '1', '1.0', 'True'], 80],
    [[0.0, 0, False, '0', '0.0', 'False'], -10]],
   'else': [0]}},
 'is_swiggy_whatsapp_absent_trigger_score': {'swiggy': {'null_check': [[0]]},
  'whatsapp': {'null_check': [[0]]},
  ('swiggy',
   'whatsapp'): {'x_and_y': [[[0.0, 0, False, '0', '0.0', 'False'],
     [0.0, 0, False, '0', '0.0', 'False'],
     -30]], 'else': [0]}},
 'has_gst_trigger_score': {'has_gst': {'null_check': [[0]],
   '==': [[[1], 50]],
   'else': [0]}},
 'numbers_in_email_trigger_score': {'input_email': {'null_check': [[0]]},
  'input_email_numbers_count': {'numbers_count': [['input_email']],
   '>': [[5, -40]],
   '<=': [[5, 0]],
   'else': [0]}},
 'tax_payer_tag': {'tax': {'null_check': [['PAN not Registered on ITR']],
   '==': [[[0.0, 0, False, '0', '0.0', 'False'],
     'PAN not Registered on ITR']]}}}